[book]
title = "Example book"
authors = ["John Doe"]
description = "The example book covers examples."
language = "en"
multilingual = false
src = "src"  # the source files

[rust]
edition = "2021"

[build]
build-dir = "book"  # the directory where the output is placed
create-missing = false
use-default-preprocessors = true  # use the default preprocessors
extra-watch-dirs = []             # directories to watch for triggering builds

[preprocessor.index]

[preprocessor.links]

[output.html]
#additional-css = ["custom.css"]

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.search]
limit-results = 15
